version: '3'
services:
  chatbot:
    build: 
      context: ./chatbot
    ports:
      - "5000:5000"
  rasa-actions:
    build: 
      context: ./rasa
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    
  
